import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart' as sb;

import '../../core/errors/app_exception.dart';
import '../../core/network/supabase_client.dart';
import '../../core/utils/app_logger.dart';
import '../models/notification_item.dart';

/// Repository for in-app notifications (auto-generated by DB triggers).
abstract interface class INotificationRepository {
  /// Fetches notifications for the current user, newest first.
  Future<List<NotificationItem>> getNotifications({
    required String userId,
    int limit,
    int offset,
  });

  /// Returns the count of unread notifications.
  Future<int> getUnreadCount(String userId);

  /// Marks a single notification as read.
  Future<void> markAsRead(String notificationId);

  /// Marks all notifications as read for the current user.
  Future<void> markAllAsRead(String userId);
}

class SupabaseNotificationRepository implements INotificationRepository {
  SupabaseNotificationRepository({this.client});

  final sb.SupabaseClient? client;

  sb.SupabaseClient get _safeClient {
    final sb.SupabaseClient? safeClient = client ?? SupabaseClientManager.client;
    if (safeClient == null) {
      throw const NetworkException(message: 'Supabase client is offline or unconfigured.');
    }
    return safeClient;
  }

  @override
  Future<List<NotificationItem>> getNotifications({
    required String userId,
    int limit = 50,
    int offset = 0,
  }) async {
    try {
      final List<Map<String, Object?>> response = await _safeClient
          .from('notifications')
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false)
          .range(offset, offset + limit - 1);

      return response.map(NotificationItem.fromJson).toList();
    } catch (e, st) {
      AppLogger.error('Error loading notifications', error: e, stackTrace: st);
      return const <NotificationItem>[];
    }
  }

  @override
  Future<int> getUnreadCount(String userId) async {
    try {
      final sb.PostgrestResponse response = await _safeClient
          .from('notifications')
          .select()
          .eq('user_id', userId)
          .eq('is_read', false)
          .count(sb.CountOption.exact);

      return response.count;
    } catch (e) {
      AppLogger.warning('Error counting unread notifications: $e', tag: 'NotificationRepo');
      return 0;
    }
  }

  @override
  Future<void> markAsRead(String notificationId) async {
    try {
      await _safeClient
          .from('notifications')
          .update(<String, Object?>{'is_read': true})
          .eq('id', notificationId);
    } catch (e, st) {
      AppLogger.error('Error marking notification as read', error: e, stackTrace: st);
    }
  }

  @override
  Future<void> markAllAsRead(String userId) async {
    try {
      await _safeClient
          .from('notifications')
          .update(<String, Object?>{'is_read': true})
          .eq('user_id', userId)
          .eq('is_read', false);
    } catch (e, st) {
      AppLogger.error('Error marking all notifications as read', error: e, stackTrace: st);
    }
  }
}

final Provider<INotificationRepository> notificationRepositoryProvider =
    Provider<INotificationRepository>((Ref ref) {
  final sb.SupabaseClient? client = ref.watch(supabaseClientProvider);
  return SupabaseNotificationRepository(client: client);
});
